#cloud-config
write_files:
  - path: /etc/NetworkManager/system-connections/static.nmconnection
    permissions: '0600'
    content: |
      [connection]
      id=static-enp1s0
      type=ethernet
      interface-name=enp1s0
      [ipv4]
      method=manual
      addresses=192.168.122.2/24
      gateway=192.168.122.1
      dns=1.1.1.1
      [ipv6]
      method=disabled

runcmd:
  - systemctl enable sshd
  - systemctl start sshd